#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo "CredPanda"
echo "coyote0x90 @ HackTheBox"
echo "Executing from $SCRIPT_DIR"

[ -f "credpanda.tried.dat" ] || touch "credpanda.tried.dat"
[ -f "services.dat" ] || touch "services.dat"

while [[ $# -gt 0 ]]; do
  case $1 in
    -u|--users)
      echo "Adding users"
      shift # pop arg
      userfile=$1
      ;;
    -p|--passwords)
      echo "Adding passwords"
      shift # pop arg
      passwordfile=$1
      ;;
    -v|--verbose) # todo
      VERBOSE=1
      ;;
    -h|--help)
      echo "Usage: $0 [ options ]"
      echo "Options:"
      cat "$0" | grep '^\s\+-.|--.*'
      exit 1
      ;;
    *)
      KB_DIR="$1"
      ;;
  esac
  shift
done

script="$SCRIPT_DIR/scripts/hydra-bruteforce-with-database.awk"
args=""
if [ ! -z "$userfile" ] && \
  [ ! -z "$passwordfile" ] && \
  [ -f "$userfile" ] && \
  [ -f "$passwordfile" ]; then
  echo doing both users and passwords
  $script type=user "$userfile" type=password "$passwordfile"
else
  echo not doing both
  if [ ! -z "$userfile" ]; then
    if [ -f "$userfile" ]; then
      $script type=user "$userfile"
    else
      echo "$userfile" | $script -v type=user
    fi
  fi
  if [ ! -z "$passwordfile" ]; then
    if [ -f "$passwordfile" ]; then
      $script type=password "$passwordfile"
    else
      echo "$passwordfile" | $script -v type=password
    fi
  fi
  if [ ! -z "$args" ]; then
    $script $args
  else
    echo "nothing to do."
  fi
fi
